insert into Game values (0, 'Chess');
insert into Game values (1, 'Checkers');

insert into Player values ('jkd', 'x', 23, 'Jan-Krzysztof', 'Duda');
insert into Player values ('magzy', 'y', 31, 'Magnus', 'Carlsen');
insert into Player values ('nepo', 'z', 31, 'Ian', 'Nepomniachtchi');
insert into Player values ('shak', 's', 36, 'Shakhriyar', 'Mamedyarov');
insert into Player values ('mvl', 'm', 31, 'Maxime', 'Vachier-Lagrave');
insert into Player values ('sasha', 'a', 38, 'Alexander', 'Grischuk');
insert into Player values ('hikaru', 'h', 34, 'Hikaru', 'Nakamura');
insert into Player values ('fabi', 'f', 29, 'Fabiano', 'Caruana');
insert into Player values ('anish', 'g', 27, 'Anish', 'Giri');
insert into Player values ('firo', 'i', 18, 'Alireza', 'Firouzja');
insert into Player values ('garry', 'rs', 58, 'Garry', 'Kasparov');
insert into Player values ('vishy', 'v', 52, 'Viswanathan', 'Anand');
insert into Player values ('radek', 'r', 35, 'Radoslaw', 'Wojtaszek');
insert into Player values ('levon', 'l', 39, 'Levon', 'Aronian');
insert into Player values ('boris', 'b', 53, 'Boris', 'Gelfand');
insert into Player values ('peter', 'p', 45, 'Peter', 'Svidler');
insert into Player values ('kramnik', 'kr', 46, 'Vladimir', 'Kramnik');
insert into Player values ('karpov', 'ak', 70, 'Anatoly', 'Karpov');
insert into Player values ('ding', 'ld', 29, 'Liren', 'Ding');
insert into Player values ('wesley', 'so', 28, 'Wesley', 'So');
insert into Player values ('richard', 'rr', 25, 'Richard', 'Rapport');
insert into Player values ('radja', 'tr', 34, 'Teimour', 'Radjabov');
insert into Player values ('leinier', 'ld', 38, 'Leinier', 'Dominguez');
insert into Player values ('wang', 'wh', 32, 'Wang', 'Hao');
insert into Player values ('vidit', 'vg', 27, 'Vidit', 'Gujrathi');
insert into Player values ('sam', 'ssh', 30, 'Sam', 'Shankland');
insert into Player values ('xiong', 'jx', 21, 'Jeffery', 'Xiong');
insert into Player values ('dubov', 'dd', 25, 'Daniil', 'Dubov');
insert into Player values ('andrey', 'ae', 19, 'Andrey', 'Esipenko');
insert into Player values ('vlad', 'va', 23, 'Vladislav', 'Artemiev');
insert into Player values ('zbychu', 'zp', 35, 'Zbigniew', 'Pakleza');
insert into Player values ('topalov', 'vt', 46, 'Veselin', 'Topalov');
insert into Player values ('chucky', 'vi', 52, 'Vasyl', 'Ivanchuk');
insert into Player values ('tari', 'at', 22, 'Aryan', 'Tari');
insert into Player values ('judit', 'jp', 45, 'Judit', 'Polgar');
insert into Player values ('jorden', 'jvf', 22, 'Jorden', 'van Foreest');
insert into Player values ('nils', 'ng', 28, 'Nils', 'Grandelius');
insert into Player values ('nodir', 'na', 17, 'Nodirbek', 'Abdusattorov');
insert into Player values ('nihal', 'ns', 17, 'Nihal', 'Sarin');
insert into Player values ('arjun', 'aer', 18, 'Arjun', 'Erigaisi');
insert into Player values ('tang', 'at', 22, 'Andrew', 'Tang');
insert into Player values ('danya', 'dn', 26, 'Daniel', 'Naroditsky');
insert into Player values ('eric', 'eh', 29, 'Eric', 'Hansen');
insert into Player values ('fedo', 'vf', 26, 'Vladimir', 'Fedoseev');
insert into Player values ('dmitry', 'da', 31, 'Dmitry', 'Andreikin');
insert into Player values ('parham', 'pm', 21, 'Parham', 'Maghsoodloo');
insert into Player values ('amin', 'at', 20, 'Amin', 'Tabatabaei');
insert into Player values ('haik', 'hm', 21, 'Haik', 'Martirosyan');
insert into Player values ('evgeny', 'et', 34, 'Evgeny', 'Tomashevsky');
insert into Player values ('nikita', 'nvv', 34, 'Nikita', 'Vitiugov');

insert into Game values (2, 'Tic Tac Toe');
